import { AxeBuilder } from "@axe-core/playwright";
import { chromium } from "playwright";
import { startPreviewServer, launchOptions } from "./scripts/server-harness.mjs";
const s = await startPreviewServer();
const b = await chromium.launch(launchOptions());
const p = await (await b.newContext({viewport:{width:1280,height:900}})).newPage();
await p.goto(s.url + "/", { waitUntil: "networkidle" });
const r = await new AxeBuilder({ page: p }).withTags(["wcag2aa"]).analyze();
for (const v of r.violations) for (const n of v.nodes) console.log(v.id, "|", n.target.join(" "), "|", (n.failureSummary||"").replace(/\n/g," "));
await b.close(); await s.close();
