/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated/_app'
import { Route as AuthenticatedAppAnalyticsRouteImport } from './routes/_authenticated/_app.analytics'
import { Route as AuthenticatedAppCouriersRouteImport } from './routes/_authenticated/_app.couriers'
import { Route as AuthenticatedAppDashboardRouteImport } from './routes/_authenticated/_app.dashboard'
import { Route as AuthenticatedAppDiagnosticsRouteImport } from './routes/_authenticated/_app.diagnostics'
import { Route as AuthenticatedAppInboxRouteImport } from './routes/_authenticated/_app.inbox'
import { Route as AuthenticatedAppProductsRouteImport } from './routes/_authenticated/_app.products'
import { Route as AuthenticatedAppSettingsRouteImport } from './routes/_authenticated/_app.settings'
import { Route as ApiPublicTelemetryRouteImport } from './routes/api/public/telemetry'
import { Route as AuthenticatedAppOrdersIndexRouteImport } from './routes/_authenticated/_app.orders.index'
import { Route as AuthenticatedAppOrdersNewRouteImport } from './routes/_authenticated/_app.orders.new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/_authenticated/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppAnalyticsRoute =
  AuthenticatedAppAnalyticsRouteImport.update({
    id: '/analytics',
    path: '/analytics',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppCouriersRoute =
  AuthenticatedAppCouriersRouteImport.update({
    id: '/couriers',
    path: '/couriers',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppDashboardRoute =
  AuthenticatedAppDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppDiagnosticsRoute =
  AuthenticatedAppDiagnosticsRouteImport.update({
    id: '/diagnostics',
    path: '/diagnostics',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppInboxRoute = AuthenticatedAppInboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppProductsRoute =
  AuthenticatedAppProductsRouteImport.update({
    id: '/products',
    path: '/products',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppSettingsRoute =
  AuthenticatedAppSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const ApiPublicTelemetryRoute = ApiPublicTelemetryRouteImport.update({
  id: '/api/public/telemetry',
  path: '/api/public/telemetry',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppOrdersIndexRoute =
  AuthenticatedAppOrdersIndexRouteImport.update({
    id: '/orders/',
    path: '/orders/',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppOrdersNewRoute =
  AuthenticatedAppOrdersNewRouteImport.update({
    id: '/orders/new',
    path: '/orders/new',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analytics': typeof AuthenticatedAppAnalyticsRoute
  '/couriers': typeof AuthenticatedAppCouriersRoute
  '/dashboard': typeof AuthenticatedAppDashboardRoute
  '/diagnostics': typeof AuthenticatedAppDiagnosticsRoute
  '/inbox': typeof AuthenticatedAppInboxRoute
  '/products': typeof AuthenticatedAppProductsRoute
  '/settings': typeof AuthenticatedAppSettingsRoute
  '/api/public/telemetry': typeof ApiPublicTelemetryRoute
  '/orders/new': typeof AuthenticatedAppOrdersNewRoute
  '/orders/': typeof AuthenticatedAppOrdersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof AuthenticatedAppAnalyticsRoute
  '/couriers': typeof AuthenticatedAppCouriersRoute
  '/dashboard': typeof AuthenticatedAppDashboardRoute
  '/diagnostics': typeof AuthenticatedAppDiagnosticsRoute
  '/inbox': typeof AuthenticatedAppInboxRoute
  '/products': typeof AuthenticatedAppProductsRoute
  '/settings': typeof AuthenticatedAppSettingsRoute
  '/api/public/telemetry': typeof ApiPublicTelemetryRoute
  '/orders/new': typeof AuthenticatedAppOrdersNewRoute
  '/orders': typeof AuthenticatedAppOrdersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated/_app': typeof AuthenticatedAppRouteWithChildren
  '/_authenticated/_app/analytics': typeof AuthenticatedAppAnalyticsRoute
  '/_authenticated/_app/couriers': typeof AuthenticatedAppCouriersRoute
  '/_authenticated/_app/dashboard': typeof AuthenticatedAppDashboardRoute
  '/_authenticated/_app/diagnostics': typeof AuthenticatedAppDiagnosticsRoute
  '/_authenticated/_app/inbox': typeof AuthenticatedAppInboxRoute
  '/_authenticated/_app/products': typeof AuthenticatedAppProductsRoute
  '/_authenticated/_app/settings': typeof AuthenticatedAppSettingsRoute
  '/api/public/telemetry': typeof ApiPublicTelemetryRoute
  '/_authenticated/_app/orders/new': typeof AuthenticatedAppOrdersNewRoute
  '/_authenticated/_app/orders/': typeof AuthenticatedAppOrdersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/couriers'
    | '/dashboard'
    | '/diagnostics'
    | '/inbox'
    | '/products'
    | '/settings'
    | '/api/public/telemetry'
    | '/orders/new'
    | '/orders/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytics'
    | '/couriers'
    | '/dashboard'
    | '/diagnostics'
    | '/inbox'
    | '/products'
    | '/settings'
    | '/api/public/telemetry'
    | '/orders/new'
    | '/orders'
  id:
    | '__root__'
    | '/'
    | '/_authenticated/_app'
    | '/_authenticated/_app/analytics'
    | '/_authenticated/_app/couriers'
    | '/_authenticated/_app/dashboard'
    | '/_authenticated/_app/diagnostics'
    | '/_authenticated/_app/inbox'
    | '/_authenticated/_app/products'
    | '/_authenticated/_app/settings'
    | '/api/public/telemetry'
    | '/_authenticated/_app/orders/new'
    | '/_authenticated/_app/orders/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedAppRoute: typeof AuthenticatedAppRouteWithChildren
  ApiPublicTelemetryRoute: typeof ApiPublicTelemetryRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/_app': {
      id: '/_authenticated/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/_app/analytics': {
      id: '/_authenticated/_app/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AuthenticatedAppAnalyticsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/couriers': {
      id: '/_authenticated/_app/couriers'
      path: '/couriers'
      fullPath: '/couriers'
      preLoaderRoute: typeof AuthenticatedAppCouriersRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/dashboard': {
      id: '/_authenticated/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedAppDashboardRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/diagnostics': {
      id: '/_authenticated/_app/diagnostics'
      path: '/diagnostics'
      fullPath: '/diagnostics'
      preLoaderRoute: typeof AuthenticatedAppDiagnosticsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/inbox': {
      id: '/_authenticated/_app/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof AuthenticatedAppInboxRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/products': {
      id: '/_authenticated/_app/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof AuthenticatedAppProductsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/settings': {
      id: '/_authenticated/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedAppSettingsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/api/public/telemetry': {
      id: '/api/public/telemetry'
      path: '/api/public/telemetry'
      fullPath: '/api/public/telemetry'
      preLoaderRoute: typeof ApiPublicTelemetryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/_app/orders/': {
      id: '/_authenticated/_app/orders/'
      path: '/orders'
      fullPath: '/orders/'
      preLoaderRoute: typeof AuthenticatedAppOrdersIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/orders/new': {
      id: '/_authenticated/_app/orders/new'
      path: '/orders/new'
      fullPath: '/orders/new'
      preLoaderRoute: typeof AuthenticatedAppOrdersNewRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
  }
}

interface AuthenticatedAppRouteChildren {
  AuthenticatedAppAnalyticsRoute: typeof AuthenticatedAppAnalyticsRoute
  AuthenticatedAppCouriersRoute: typeof AuthenticatedAppCouriersRoute
  AuthenticatedAppDashboardRoute: typeof AuthenticatedAppDashboardRoute
  AuthenticatedAppDiagnosticsRoute: typeof AuthenticatedAppDiagnosticsRoute
  AuthenticatedAppInboxRoute: typeof AuthenticatedAppInboxRoute
  AuthenticatedAppProductsRoute: typeof AuthenticatedAppProductsRoute
  AuthenticatedAppSettingsRoute: typeof AuthenticatedAppSettingsRoute
  AuthenticatedAppOrdersNewRoute: typeof AuthenticatedAppOrdersNewRoute
  AuthenticatedAppOrdersIndexRoute: typeof AuthenticatedAppOrdersIndexRoute
}

const AuthenticatedAppRouteChildren: AuthenticatedAppRouteChildren = {
  AuthenticatedAppAnalyticsRoute: AuthenticatedAppAnalyticsRoute,
  AuthenticatedAppCouriersRoute: AuthenticatedAppCouriersRoute,
  AuthenticatedAppDashboardRoute: AuthenticatedAppDashboardRoute,
  AuthenticatedAppDiagnosticsRoute: AuthenticatedAppDiagnosticsRoute,
  AuthenticatedAppInboxRoute: AuthenticatedAppInboxRoute,
  AuthenticatedAppProductsRoute: AuthenticatedAppProductsRoute,
  AuthenticatedAppSettingsRoute: AuthenticatedAppSettingsRoute,
  AuthenticatedAppOrdersNewRoute: AuthenticatedAppOrdersNewRoute,
  AuthenticatedAppOrdersIndexRoute: AuthenticatedAppOrdersIndexRoute,
}

const AuthenticatedAppRouteWithChildren =
  AuthenticatedAppRoute._addFileChildren(AuthenticatedAppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedAppRoute: AuthenticatedAppRouteWithChildren,
  ApiPublicTelemetryRoute: ApiPublicTelemetryRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
